#if !defined(AFX_EDENSOCKET_H__08E3E534_DD63_48A2_970B_A5418F24CF86__INCLUDED_)
#define AFX_EDENSOCKET_H__08E3E534_DD63_48A2_970B_A5418F24CF86__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CEdenSocket wrapper class

class CEdenSocket : public CWnd
{
protected:
	DECLARE_DYNCREATE(CEdenSocket)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x5659f5b6, 0x7af7, 0x4b8c, { 0xb9, 0x39, 0x8e, 0xa4, 0x37, 0x1e, 0xdc, 0xc9 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetAddSH();
	void SetAddSH(BOOL);
	BOOL GetStripCCSDS();
	void SetStripCCSDS(BOOL);
	BOOL GetAddCCSDS();
	void SetAddCCSDS(BOOL);

// Operations
public:
	BOOL Create(long nPort);
	BOOL SendCmdAnsw(long nStatus, LPCTSTR szCmd);
	BOOL SendTmScoe(long nApid, const VARIANT& pData, long nLen);
	BOOL SendTmSpace(long nApid, const VARIANT& pData, long nLen);
	BOOL SendTcA(long nStatus, long nTCID);
	BOOL Connect(LPCTSTR szHostAddress, long nPort);
	BOOL Disconnect();
	BOOL SendTcE(long nStatus, long nTCID, const VARIANT& pData, long nLen);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EDENSOCKET_H__08E3E534_DD63_48A2_970B_A5418F24CF86__INCLUDED_)
